"""
export_utils.py
===============
Exports the generated summaries to downloadable file formats.

Supported formats:
- Plain text (.txt)  – zero dependencies
- PDF (.pdf)         – uses ReportLab (pure-Python, no system deps)
"""

import io
from datetime import datetime
from typing import Any


# ─────────────────────────────────────────────────
# TXT Export
# ─────────────────────────────────────────────────
def export_to_txt(summaries: dict, video_id: str) -> bytes:
    """
    Render all summary sections as a nicely formatted plain-text document.

    Args:
        summaries: Dict returned by generate_all_summaries().
        video_id:  YouTube video ID (used in the header).

    Returns:
        UTF-8 encoded bytes ready for st.download_button().
    """
    lines = []
    sep   = "=" * 60

    lines.append(sep)
    lines.append(f"  YouTube AI Summary")
    lines.append(f"  Video : https://youtu.be/{video_id}")
    lines.append(f"  Date  : {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(sep)
    lines.append("")

    # ── Title ──
    title = summaries.get("title", "Video Summary")
    lines.append(f"TITLE: {title}")
    lines.append("")

    # ── TL;DR ──
    lines.append("TL;DR")
    lines.append("-" * 40)
    lines.append(summaries.get("tldr", "N/A"))
    lines.append("")

    # ── Summary ──
    lines.append("OVERALL SUMMARY")
    lines.append("-" * 40)
    lines.append(summaries.get("summary", "N/A"))
    lines.append("")

    # ── Key Insights ──
    lines.append("KEY INSIGHTS")
    lines.append("-" * 40)
    for i, insight in enumerate(summaries.get("insights", []), 1):
        lines.append(f"  {i}. {insight}")
    lines.append("")

    # ── Topics / Timestamps ──
    lines.append("IMPORTANT TOPICS & TIMESTAMPS")
    lines.append("-" * 40)
    for topic in summaries.get("topics", []):
        ts   = topic.get("timestamp", "")
        name = topic.get("topic", "")
        desc = topic.get("description", "")
        lines.append(f"  [{ts}] {name} – {desc}")
    lines.append("")

    # ── Keywords ──
    keywords = summaries.get("keywords", [])
    if keywords:
        lines.append("KEYWORDS")
        lines.append("-" * 40)
        lines.append("  " + ", ".join(keywords))
        lines.append("")

    lines.append(sep)
    lines.append("Generated by YouTube AI Summarizer")
    lines.append(sep)

    return "\n".join(lines).encode("utf-8")


# ─────────────────────────────────────────────────
# PDF Export
# ─────────────────────────────────────────────────
def export_to_pdf(summaries: dict, video_id: str) -> bytes:
    """
    Render all summary sections as a styled PDF using ReportLab.

    Falls back to a UTF-8 encoded TXT wrapped in bytes if ReportLab
    is not installed, so the download button still works.

    Args:
        summaries: Dict returned by generate_all_summaries().
        video_id:  YouTube video ID.

    Returns:
        PDF bytes (or plain-text bytes as fallback).
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer,
            HRFlowable, Table, TableStyle,
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()

        # ── Custom styles ──
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Title"],
            fontSize=22,
            textColor=colors.HexColor("#667eea"),
            spaceAfter=6,
            alignment=TA_LEFT,
        )
        heading_style = ParagraphStyle(
            "CustomHeading",
            parent=styles["Heading2"],
            fontSize=13,
            textColor=colors.HexColor("#764ba2"),
            spaceBefore=14,
            spaceAfter=4,
        )
        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=15,
            spaceAfter=4,
        )
        meta_style = ParagraphStyle(
            "Meta",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=2,
        )
        tldr_style = ParagraphStyle(
            "TLDR",
            parent=styles["Normal"],
            fontSize=11,
            leading=16,
            textColor=colors.HexColor("#333366"),
            backColor=colors.HexColor("#f0f0ff"),
            borderPadding=(8, 10, 8, 10),
            fontName="Helvetica-Oblique",
        )

        story = []

        # ── Header ──
        story.append(Paragraph("🎬 YouTube AI Summary", title_style))
        story.append(Paragraph(summaries.get("title", "Video Summary"), heading_style))
        story.append(Paragraph(f"https://youtu.be/{video_id}", meta_style))
        story.append(Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            meta_style,
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#667eea")))
        story.append(Spacer(1, 0.3 * cm))

        # ── TL;DR ──
        story.append(Paragraph("⚡ TL;DR", heading_style))
        story.append(Paragraph(summaries.get("tldr", "N/A"), tldr_style))
        story.append(Spacer(1, 0.3 * cm))

        # ── Summary ──
        story.append(Paragraph("📋 Overall Summary", heading_style))
        story.append(Paragraph(
            summaries.get("summary", "N/A").replace("\n", "<br/>"),
            body_style,
        ))

        # ── Key Insights ──
        story.append(Paragraph("💡 Key Insights", heading_style))
        for i, insight in enumerate(summaries.get("insights", []), 1):
            story.append(Paragraph(f"{i}. {insight}", body_style))

        # ── Topics / Timestamps ──
        topics = summaries.get("topics", [])
        if topics:
            story.append(Paragraph("⏱️ Important Topics", heading_style))
            table_data = [["Time", "Topic", "Description"]]
            for t in topics:
                table_data.append([
                    t.get("timestamp", ""),
                    t.get("topic", ""),
                    t.get("description", ""),
                ])
            table = Table(table_data, colWidths=[2.5 * cm, 4 * cm, 10 * cm])
            table.setStyle(TableStyle([
                ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#667eea")),
                ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
                ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",    (0, 0), (-1, 0), 10),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f7ff")]),
                ("FONTSIZE",    (0, 1), (-1, -1), 9),
                ("GRID",        (0, 0), (-1, -1), 0.4, colors.HexColor("#ccccee")),
                ("VALIGN",      (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING",  (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(table)

        # ── Keywords ──
        keywords = summaries.get("keywords", [])
        if keywords:
            story.append(Paragraph("🔑 Keywords", heading_style))
            story.append(Paragraph("  •  ".join(keywords), body_style))

        # ── Footer ──
        story.append(Spacer(1, 0.5 * cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Paragraph(
            "Generated by YouTube AI Summarizer · Powered by LangChain & Streamlit",
            meta_style,
        ))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        # ReportLab not installed — return the TXT content instead
        return export_to_txt(summaries, video_id)
    except Exception:
        return export_to_txt(summaries, video_id)
